### ISSUE TITLE
Problém s posíláním ověřovacích emailů 

### ISSUE THREAD

**Issue by turcinv** [xaralis/ksicht#26]
Ahoj, ta nová verze stránek jede, ale máme trochu problém, registrace nových uživatelů nejde, protože uživateli nepřijde email a celkově rozesílání emailů nefunguje, nevíš, čím by to mohlo být? Já fakt netuším, co se děje, všechno jsem udělal dle postupu akorát tohle nefunguje
@xaralis

**Comment by turcinv** [comment]
Problém je s migrací databáze, já jsem si nevšiml, ale to budu muset řešit se správcem, abych dostal více práv

**Comment by xaralis** [comment]
No tak já teď nevím co s tím mám dělat. DB migrace mi přijde, že spuštěny byly. Pokud nechodí emaily, je potřeba to řešit se správcem serveru, já s tím nic přímo neudělám.

**Comment by turcinv** [comment]
Mohlo by to být tím, že docker-compose.yml spouštím ze své složky? @xaralis

**Comment by turcinv** [comment]
Prý mám úplně stejná práva jako ty, ale stále mi to nejde
A jediné co, tak nemám práva ke tvé složce, tak jsem to spustil ze své složky, která je kopií té tvé

**Comment by xaralis** [comment]
Nevím co ti nejde. docker-compose každopádně je nutné pouštět z toho původního umístění, jinak to IMO logicky docker nebude považovat za to samé.

**Comment by turcinv** [comment]
Aha, jestli je nutné to spouštět z původního umístění, tak v tom případě moc moc prosím, abys to spustil ty, já nemám práva ke tvé složce
Nejde migrace databází, tudíž nejdou Ksichtí emaily a registrace a hází to error 500

**Comment by turcinv** [comment]
Hrozně moc se Ti omlouvám, pokazil jsem to

**Comment by xaralis** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/441739/187651374-947ccffc-40a7-4d2a-8027-dd071b574e4b.png">

Nevím, zdá se, že migrace spuštěné byly.

**Comment by turcinv** [comment]
Aha, tak to je problém teda jinde, je pravda, že při prvním spuštění mi to migraci udělalo, v tom případě porblém bude úplně někde jinde, tak to se znovu omlouvám

**Comment by xaralis** [comment]
Chodí vám prosím ty error logy z Djanga? Jestli ne tak prosím email a já to přepošlu.

**Comment by xaralis** [comment]
IntegrityError at /aktualni-rocnik/prihlasit-se/
insert or update on table "core_gradeapplication" violates foreign key constraint "core_gradeapplicatio_participant_id_045c5330_fk_core_part"
DETAIL:  Key (participant_id)=(883) is not present in table "core_participant_org".

**Comment by turcinv** [comment]
Errory mi nechodí, zde je email vitturcin@gmail.com

**Comment by xaralis** [comment]
@turcinv Přeposlal jsem. Plus byste pak měli udělat MR na přidání se do `ADMINS` aby to chodilo i na vás.

**Comment by turcinv** [comment]
Dobře, provedu, děkuji za pomoc, fakt jsi záchrana
